### ISSUE TITLE
Please upload the scripts folder 

### ISSUE THREAD

**Issue by eecrazy** [qiangning/CogCompTime#1]
I see that you filter many folders in you git ignore file, please upload the necessary folders, such as the scripts folder, and maybe also the models folder.

Thank you!

**Comment by qiangning** [comment]
Hi there,

Thanks for catching up this. I didn't put the `models/` folder because it's should not be necessary. I have packaged the models into a jar file and they're actually claimed in the pom file: https://github.com/qiangning/CogCompTime/blob/master/pom.xml#L19. 

Regarding the `scripts/` folder, I just realized that you're right. I have updated the repo with it. Thanks again.

**Comment by eecrazy** [comment]
Thank you, this is helpful!
